apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-view-base
  labels:
    app: deploy-view-base
spec:
  replicas: 3
  selector:
    matchLabels:
      app: view-base
  template:
    metadata:
      labels:
        app: view-base
    spec:
      containers:
      - name: view-base
        image: view-base:1.0.0
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: svc-view-base
  labels:
    app: svc-view-base
spec:
  type: NodePort
  selector:
    app: view-base
  ports:
  - port: 80
    targetPort: 8080
